from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from runtime.app import MainApp

APP_INSTANCE: "MainApp"

MENUBAR_BUTTON_NEW= 0
MENUBAR_BUTTON_LOAD= 1
MENUBAR_BUTTON_RECENTS= 2
MENUBAR_BUTTON_SAVE= 3
MENUBAR_BUTTON_SAVEAS= 4

ICON_FILE= 0
ICON_NEW= 1
ICON_RECENTS= 2
ICON_LOAD= 3
ICON_SAVE= 4
ICON_SAVEAS= 5

ICON_EDIT= 8
ICON_UNLOCK= 9
ICON_INCREMENT= 10
ICON_DECREMENT= 11

ICON_FILE_DISABLED= 48
ICON_NEW_DISABLED= 49
ICON_RECENTS_DISABLED= 50
ICON_LOAD_DISABLED= 51
ICON_SAVE_DISABLED= 52
ICON_SAVEAS_DISABLED= 53

ICON_EDIT_DISABLED= 56
ICON_UNLOCK_DISABLED= 57
ICON_INCREMENT_DISABLED= 58
ICON_DECREMENT_DISABLED= 59